# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
              class: AppBundle:User
              property: email
#        in_memory:
#            memory:
#              users:
#                admin:
#                  password: 123456
#                  roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        main:
            pattern:    ^/admin
            http_basic: ~
            provider: our_db_provider

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }
