services:
    app.admin.test:
        class: AppBundle\Admin\TestAdmin
        arguments: [~, AppBundle\Entity\Test, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: test, label: Тесты }
        public: true

    app.admin.classes:
        class: AppBundle\Admin\ClassesAdmin
        arguments: [~, AppBundle\Entity\Classes, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: classes, label: Классы }
        public: true

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: students, label: Ученики }
        public: true

#    app.admin.admin_user:
#        class: AppBundle\Admin\AdminUserAdmin
#        arguments: [~, AppBundle\Entity\User, Sonata\AdminBundle\Controller\CRUDController]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: users, label: Пользователи }
#        public: true
