services:
    app.service.calculation:
        class: AppBundle\Service\Calculation
        autowire: false
        arguments:
           - "@doctrine.orm.default_entity_manager"

    app.validator.class_exists:
        class: AppBundle\Validator\Constraints\ClassExistsValidator
        autowire: false
        arguments:
          - "@doctrine.orm.default_entity_manager"
        tags: ['validator.constraint_validator']

    app.validator.email_exists:
            class: AppBundle\Validator\Constraints\EmailExistsValidator
            autowire: false
            arguments:
              - "@doctrine.orm.default_entity_manager"
            tags: ['validator.constraint_validator']

    app.service.file_uploader:
            class: AppBundle\Service\FileUploader
            arguments:
              $targetDirectory: '%kernel.root_dir%/../web/uploads/'
